### PR TITLE
Fix MethodName for nested classes

### LINKED ISSUE #1557: MethodName check fails on constructor of nested class
### Description
MethodName check misidentifies the constructor of a nested class as a method

### Steps to reproduce the problem
Add this to `cxx-checks/src/test/resources/checks/MethodName.cc` and run `mvn test`
```
class OuterClass {
  class Inner_Class {
    Inner_Class();
  };
};

OuterClass::Inner_Class::Inner_Class()
{
}
```

### Expected behavior
That `Inner_Class` constructor would not fail MethodName check.

### Actual behavior
`Inner_Class` constructor fails MethodName check.

### Known workarounds

Please provide a description of any known workarounds.

### LOG file
Output from `mvn test`
```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.018 s <<< FAILURE! - in org.sonar.cxx.checks.naming.MethodNameCheckTest
[ERROR] test(org.sonar.cxx.checks.naming.MethodNameCheckTest)  Time elapsed: 0.018 s  <<< FAILURE!
java.lang.AssertionError: 

No more violations expected
got: at line 51
        at org.sonar.cxx.checks.naming.MethodNameCheckTest.test(MethodNameCheckTest.java:50)
```
### Related information

* cxx plugin version: latest master 2018-09-21 (g071070...). Same result in 1.1.0
* SonarQube version: 6.7.5

### PR DESCRIPTION
**Pull request by ivangalkin**
Fix MethodNameCheck, especially the detection of the most nested (and the most relevant) type.
* take into account, that `nestedNameSpecifier` doesn't chain `typeName`s
* it might chain
   * `typeName`
   * `simpleTemplateId`s
   * `IDENTIFIER`s
* go through all childrens of `nestedNameSpecifier` and find the last one, which matches the types from the list above. This last AstNode will represent the most-nested type name

closes #1557

---
This change is [Reviewable](https://reviewable.io/reviews/sonaropencommunity/sonar-cxx/1559)

### CODE REVIEW

File: cxx-checks/src/main/java/org/sonar/cxx/checks/naming/MethodNameCheck.java [hunk 1]
```diff
@@ -118,7 +118,7 @@ AstNode getOutsideMemberDeclaration(AstNode declId) {
     if (nestedNameSpecifier != null) {
       AstNode idNode = declId.getLastChild(CxxGrammarImpl.className);
       if (idNode != null) {
-        AstNode className = nestedNameSpecifier.getFirstDescendant(CxxGrammarImpl.className);
+        AstNode className = nestedNameSpecifier.getLastChild(CxxGrammarImpl.className);
```
Comment (ivangalkin) [inline cxx-checks/src/main/java/org/sonar/cxx/checks/naming/MethodNameCheck.java]: `getLastChild()` addresses the most significant / most outer class name

```
  functionDefinition ==
     [namespaces...]::className0::className1::className2::ID
                                              ^^^^^^^^^^
```

This forces us to express the `nestedNameSpecifier` in terms of one or many repeating `className`s

File: cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java [hunk 2]
```diff
@@ -502,15 +502,12 @@ private static void expressions(LexerfulGrammarBuilder b) {
     b.rule(nestedNameSpecifier).is(
       b.firstOf(
         "::",
-        b.sequence(typeName, "::"), // C++
+        b.sequence(className, "::"), // C++
```
Comment (ivangalkin) [inline cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java]: Unfortunately `nestedNameSpecifier` was not expressed in terms of `className`s. 

* `typeName` is theoretically a super-set w.r.t. the `className`but practically it's completely interchangeable with `className`. See below




```JAVA
    b.rule(typeName).is(
      b.firstOf(
        className,       // == b.firstOf( simpleTemplateId, IDENTIFIER )
        enumName,        // == IDENTIFIER
        typedefName,     // == IDENTIFIER
        simpleTemplateId // 
      )
    );
```
but the real problem lies below...

File: cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java [hunk 3]
```diff
@@ -502,15 +502,12 @@ private static void expressions(LexerfulGrammarBuilder b) {
...
         b.sequence(namespaceName, "::"), // C++
         b.sequence(decltypeSpecifier, "::") // C++
       ),
       b.zeroOrMore(
-        b.firstOf(
-          b.sequence(IDENTIFIER, "::"), // C++
-          b.sequence(b.optional(CxxKeyword.TEMPLATE), simpleTemplateId, "::") // C++
-        )
+          b.sequence(className, "::") // C++
```
Comment (ivangalkin) [inline cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java]: we cannot address the nested identifiers like `className0::className1::className2` as long as we use "raw" `IDENTIFIER`s. Or can we?

**Comment by guwirth** [comment]
@ivangalkin had no time to have a deeper look but one hint: we should not change the grammar to support feature. The current grammar is more or less 1:1 aligned with the C++ standard.

**Comment by ivangalkin** [comment]
Hello @guwirth 

>The current grammar is more or less 1:1 aligned with the C++ standard.

unfortunately it's not really 1:1, especially in the affected part. `nested-name-specifier` has a recursive definition (see e.g. http://www.nongnu.org/hcb/#nested-name-specifier)
```BNF
nested-name-specifier: 	 
  	type-name ::
  	namespace-name ::
  	decltype-specifier ::     C++0x
  	nested-name-specifier identifier ::
  	nested-name-specifier templateopt simple-template-id ::
```

After AST was built-up one always can access the chain of `type-name`s. This chain should be later evaluated in order to detect the ctor/dtor definition and skip it (we are interested in the last/most nested `type-name` actually).

If you compare the original grammar with the definition of the `nestedNameSpecifier` in `CxxGrammarImpl` you won't see any recursion. Moreover the sequence of `typeName`s seems to be implemented in the wrong way.

```C++
b.rule(nestedNameSpecifier).is(
  b.firstOf(
    "::",
    b.sequence(typeName, "::"), // C++
    b.sequence(namespaceName, "::"), // C++
    b.sequence(decltypeSpecifier, "::") // C++
  ),
  b.zeroOrMore(
    b.firstOf(
      b.sequence(IDENTIFIER, "::"), // C++
      b.sequence(b.optional(CxxKeyword.TEMPLATE), simpleTemplateId, "::") // C++
    )
  )
);
```

Example 1:

```CPP
// simple nested class
class My_Class {

  class My_Inner_Class {
    My_Inner_Class();
  };
};

My_Class::My_Inner_Class::My_Inner_Class()
{
}

```

the line `My_Class::My_Inner_Class::My_Inner_Class()` is parsed as

```XML
<nestedNameSpecifier tokenValue="My_Class" tokenLine="8" tokenColumn="0">
  <typeName tokenValue="My_Class" tokenLine="8" tokenColumn="0">
    <className tokenValue="My_Class" tokenLine="8" tokenColumn="0">
      <IDENTIFIER tokenValue="My_Class" tokenLine="8" tokenColumn="0"/>
    </className>
  </typeName>

  <DOUBLECOLON tokenValue="::" tokenLine="8" tokenColumn="8"/>
  <IDENTIFIER tokenValue="My_Inner_Class" tokenLine="8" tokenColumn="10"/>
  <DOUBLECOLON tokenValue="::" tokenLine="8" tokenColumn="24"/>

</nestedNameSpecifier>
<className tokenValue="My_Inner_Class" tokenLine="8" tokenColumn="26">
  <IDENTIFIER tokenValue="My_Inner_Class" tokenLine="8" tokenColumn="26"/>
</className>
```

So we don't see a required `typeName::typeName::className` but rather `typeName::IDENTIFIER::className`. I am not sure about the correctness of the `className`, but the important part is the missing nested `typeName`. The inability to parse the nested `typeName` becomes more critical if the `type-name` is e.g. a template.

Example 2
```CPP
// nested class is a template
class My_Class {
  template<typename T1, typename T2, typename T3>
  class My_Inner_Class {
    My_Inner_Class();
  };
};

template<typename T1, typename T2, typename T3>
My_Class::My_Inner_Class<T1, T2, T3>::My_Inner_Class()
{
}
```

In this case again there is no logical grouping for `My_Inner_Class<T1, T2, T3>`. The `nestedNameSpecifier` is `typeName::simpleTemplateId::className` (you'll find the full AST below if you are interested in it).

The summary of my evaluation is:

* I believe our grammar is wrong w.r.t. `nestedNameSpecifier`
* I believe `nestedNameSpecifier` misses a logical grouping for nested types
* I think it's possible to query the `nestedNameSpecifier` after the most nested type name, but it is not an universal/robust/safe solution
1. query after the last direct-child of type `IDENTIFIER` (see example 1)
2. query after the last direct-child of type `simpleTemplateId` (see example 2)
3. compare, which construct (1 or 2) is really the last one, extract the first token value and *hope* that it's a type name
* I believe, that my patch it not correct in terms of the original C++ BNF (again, there is no recursion, I used `className` instead of `typeName` etc), but I think it doesn't cut the existing grammar. I would be happy if someone suggests the proper fix of the CxxGrammarImpl.

@ALL does anybody know if Sonar-SSLR supports the recursive grammar definition? why don't we define `nestedNameSpecifier` recursively?


P.S. nestedNameSpecifier from example 2
```XML
<nestedNameSpecifier tokenValue="My_Class" tokenLine="10" tokenColumn="0">
  <typeName tokenValue="My_Class" tokenLine="10" tokenColumn="0">
    <className tokenValue="My_Class" tokenLine="10" tokenColumn="0">
      <IDENTIFIER tokenValue="My_Class" tokenLine="10" tokenColumn="0"/>
    </className>
  </typeName>
  <DOUBLECOLON tokenValue="::" tokenLine="10" tokenColumn="8"/>
  <simpleTemplateId tokenValue="My_Inner_Class" tokenLine="10" tokenColumn="10">
    <templateName tokenValue="My_Inner_Class" tokenLine="10" tokenColumn="10">
      <IDENTIFIER tokenValue="My_Inner_Class" tokenLine="10" tokenColumn="10"/>
    </templateName>
    <LT tokenValue="<" tokenLine="10" tokenColumn="24"/>
    <templateArgumentList tokenValue="T1" tokenLine="10" tokenColumn="25">
      <templateArgument tokenValue="T1" tokenLine="10" tokenColumn="25">
        <typeId tokenValue="T1" tokenLine="10" tokenColumn="25">
          <typeSpecifierSeq tokenValue="T1" tokenLine="10" tokenColumn="25">
            <typeSpecifier tokenValue="T1" tokenLine="10" tokenColumn="25">
              <trailingTypeSpecifier tokenValue="T1" tokenLine="10" tokenColumn="25">
                <simpleTypeSpecifier tokenValue="T1" tokenLine="10" tokenColumn="25">
                  <typeName tokenValue="T1" tokenLine="10" tokenColumn="25">
                    <className tokenValue="T1" tokenLine="10" tokenColumn="25">
                      <IDENTIFIER tokenValue="T1" tokenLine="10" tokenColumn="25"/>
                    </className>
                  </typeName>
                </simpleTypeSpecifier>
              </trailingTypeSpecifier>
            </typeSpecifier>
          </typeSpecifierSeq>
        </typeId>
      </templateArgument>
      <COMMA tokenValue="," tokenLine="10" tokenColumn="27"/>
      <templateArgument tokenValue="T2" tokenLine="10" tokenColumn="29">
        <typeId tokenValue="T2" tokenLine="10" tokenColumn="29">
          <typeSpecifierSeq tokenValue="T2" tokenLine="10" tokenColumn="29">
            <typeSpecifier tokenValue="T2" tokenLine="10" tokenColumn="29">
              <trailingTypeSpecifier tokenValue="T2" tokenLine="10" tokenColumn="29">
                <simpleTypeSpecifier tokenValue="T2" tokenLine="10" tokenColumn="29">
                  <typeName tokenValue="T2" tokenLine="10" tokenColumn="29">
                    <className tokenValue="T2" tokenLine="10" tokenColumn="29">
                      <IDENTIFIER tokenValue="T2" tokenLine="10" tokenColumn="29"/>
                    </className>
                  </typeName>
                </simpleTypeSpecifier>
              </trailingTypeSpecifier>
            </typeSpecifier>
          </typeSpecifierSeq>
        </typeId>
      </templateArgument>
      <COMMA tokenValue="," tokenLine="10" tokenColumn="31"/>
      <templateArgument tokenValue="T3" tokenLine="10" tokenColumn="33">
        <typeId tokenValue="T3" tokenLine="10" tokenColumn="33">
          <typeSpecifierSeq tokenValue="T3" tokenLine="10" tokenColumn="33">
            <typeSpecifier tokenValue="T3" tokenLine="10" tokenColumn="33">
              <trailingTypeSpecifier tokenValue="T3" tokenLine="10" tokenColumn="33">
                <simpleTypeSpecifier tokenValue="T3" tokenLine="10" tokenColumn="33">
                  <typeName tokenValue="T3" tokenLine="10" tokenColumn="33">
                    <className tokenValue="T3" tokenLine="10" tokenColumn="33">
                      <IDENTIFIER tokenValue="T3" tokenLine="10" tokenColumn="33"/>
                    </className>
                  </typeName>
                </simpleTypeSpecifier>
              </trailingTypeSpecifier>
            </typeSpecifier>
          </typeSpecifierSeq>
        </typeId>
      </templateArgument>
    </templateArgumentList>
    <GT tokenValue=">" tokenLine="10" tokenColumn="35"/>
  </simpleTemplateId>
  <DOUBLECOLON tokenValue="::" tokenLine="10" tokenColumn="36"/>
</nestedNameSpecifier>
```

**Comment by guwirth** [comment]
@ivangalkin thx for your explanation. Will have a closer look to it and will come back to you...

**Comment by guwirth** [comment]
@ivangalkin I tested nested-name-specifier with #1562 again. Looks good. Think the real problem is that we have no symbol table and eyerything is a keyword or an identifier at the end. In a nested name the parser can’t know if an token is a namespace name, a class name, a template name, enum name, typedef name, ... .
It’s more or less always `(::)*(identifier ::)+`.
Nevertheless I would not change / optimize the grammar because this makes it very difficult to maintain and extend it. Would extend the check to take this into account.

File: cxx-checks/src/test/resources/checks/MethodName.cc [hunk 4]
```diff
@@ -46,4 +64,29 @@ test::My_Class::~My_Class() // not an error
...
+
+template<typename T>
+My_Class::My_Inner_Class_With_Template<T>::Third_Level_Nested_Class::Third_Level_Nested_Class() // not an error
+{
+}
+
+template<typename T>
+void My_Class::My_Inner_Class_With_Template<T>::Third_Level_Nested_Class::Third_Level_Nested_Class_getX() // error
+{
+}
```
Comment (guwirth) [inline cxx-checks/src/test/resources/checks/MethodName.cc]: Would add also a namespace and decltype specifier sample to be complete.

File: cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java (hunk 2 above)
Comment (guwirth) [inline cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java]: Parser can’t know what it is because of missing symbol table.

File: cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java (hunk 3 above)
Comment (guwirth) [reply cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java]: Is not really a fix, makes it only easier to write the check.
