### PR TITLE
consume empty VS coverage report

### LINKED ISSUE #1231: NullPointerException when passing empty coverage report
Hello,
When passing an empty (yet valid) coverage report to the plugin, sonar scanner crashes with the following stack-trace : 

> WARN: Coverage report /path/to/coverage/empty-report.xml result is empty (parsed by VisualStudioParser)
> ERROR: Error during SonarQube Scanner execution
> java.lang.NullPointerException
> 	at java.util.HashMap.putMapEntries(HashMap.java:500)
> 	at java.util.HashMap.putAll(HashMap.java:784)
> 	at org.sonar.cxx.sensors.coverage.CxxCoverageSensor.processReports(CxxCoverageSensor.java:249)
> 	at org.sonar.cxx.sensors.coverage.CxxCoverageSensor.execute(CxxCoverageSensor.java:135)
> 	at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:182)
> 	at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57)
> 	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
> 	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
> 	at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
> 	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
> 	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
> 	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
> 	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:234)
> 	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
> 	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
> 	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
> 	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
> 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
> 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
> 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
> 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
> 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
> 	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
> 	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
> 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

I'm attaching you the empty coverage report you can use to reproduce.

I must precise that I have this bug after "upgrading" to a snapshot of the master as of today. It previously worked fine with the release 0.9.7 version ("worked fine" means that the report was ignored without crashing the scanner).

Thanks
-dutiona

[empty-report.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/1296265/empty-report.zip)

### PR DESCRIPTION
**Pull request by Bertk**
close #1231 
- empty VS coverage reports create NullPointerException and not EmptyReportException

---
This change is [Reviewable](https://reviewable.io/reviews/sonaropencommunity/sonar-cxx/1232)

### CODE REVIEW

File: cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CxxCoverageSensor.java [hunk 1]
```diff
@@ -247,7 +247,7 @@ private void saveZeroValueForResource(InputFile inputFile, SensorContext context
             }
           }
           measuresTotal.putAll(cacheCov.get(report.getAbsolutePath()));
```
Comment (guwirth) [inline cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CxxCoverageSensor.java]: will throw a NullPointerException because `cacheCov.get(report.getAbsolutePath())`returns `null`

File: cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CxxCoverageSensor.java [hunk 2]
```diff
@@ -247,7 +247,7 @@ private void saveZeroValueForResource(InputFile inputFile, SensorContext context
...
-        } catch (EmptyReportException e) {
+        } catch (EmptyReportException | NullPointerException e) {
```
Comment (guwirth) [inline cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CxxCoverageSensor.java]: should catch only EmptyReportException

File: cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CxxCoverageSensor.java (hunk 1 above)
Comment (guwirth) [reply cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CxxCoverageSensor.java]: `parseCoverageReport' XMLStreamException is not working in case of empty report?
Strange: Throwing first and then trying to write a message?

```Java
try {
       parser.processReport(context, report, measuresForReport);
     } catch (XMLStreamException e) {
       throw new EmptyReportException("Coverage report" + report + "cannot be parsed by" + parser, e); 
     }
 
     if (measuresForReport.isEmpty()) {
       LOG.warn("Coverage report {} result is empty (parsed by {})", report, parser);
       return false;
}
```

File: cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CxxCoverageSensor.java (hunk 2 above)
Comment (Bertk) [reply cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CxxCoverageSensor.java]: Unfortunately this sensor uses a mixture of exception and Boolean return value for handling the results :unamused:
By the way, we should not use null for empty results but an empty collection.

Comment (Bertk) [reply cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CxxCoverageSensor.java]: cacheCov.get(report.getAbsolutePath()) returns null but should return an empty map ```Map<String, CoverageMeasures>>```

**Comment by guwirth** [comment]
@Bertk thx a lot.
