### PR TITLE
ISSUE-2916 - First working version with ssl context

### LINKED ISSUE #2916: sonar-cxx 2.2.1.1225 fails with SSLHandshakeException on SonarQube 2025.1.1
**Describe the bug**
After upgrading our SonarQube instance from version 8.0.1+546 to 2025.1.1, our sonar-scanner jobs are failing to retrieve rules from the SonarQube server due to a `javax.net.ssl.SSLHandshakeException`. This issue specifically manifests when using the sonar-cxx plugin version 2.2.1.1225. We have followed the TLS certificate management documentation provided by SonarSource but the issue persists.

**To Reproduce**
1. Execute a sonar-scanner job from our GitLab CI pipeline. This job runs within a custom Docker image that includes all necessary build tools and the sonar-scanner.
2. The sonar-scanner attempts to connect to our SonarQube instance (version 2025.1.1) to retrieve quality profiles and rules for C++ analysis.
3. The scanner fails with a `javax.net.ssl.SSLHandshakeException`, indicating a failure to establish a secure connection.

**Expected behavior**
The sonar-scanner should successfully connect to the SonarQube server, retrieve the necessary quality profiles and rules for the sonar-cxx plugin, and proceed with the analysis of our C++ codebase without any SSL-related errors.

**Screenshots**
```
08:33:17.402 INFO  Processing successful, saved new issues=941
08:33:17.402 INFO  Sensor CXX Cppcheck report import [cxx] (done) | time=267ms
08:33:17.402 INFO  Sensor CXX Clang-Tidy report import [cxx]
08:33:17.402 INFO  Downloading rules for 'clangtidy' from server '************'
08:33:17.421 WARN  Rules for 'clangtidy' could not be loaded from server
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(Unknown Source)
	at org.sonar.cxx.sensors.utils.SonarServerWebApi.get(SonarServerWebApi.java:127)
	at org.sonar.cxx.sensors.utils.SonarServerWebApi.getRules(SonarServerWebApi.java:85)
	at org.sonar.cxx.sensors.utils.CxxIssuesReportSensor.downloadRulesFromServer(CxxIssuesReportSensor.java:103)
	at org.sonar.cxx.sensors.utils.CxxIssuesReportSensor.executeImpl(CxxIssuesReportSensor.java:88)
	at org.sonar.cxx.sensors.utils.CxxReportSensor.execute(CxxReportSensor.java:101)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
	at org.sonar.scanner.sensor.ProjectSensorsExecutor.execute(ProjectSensorsExecutor.java:54)
	at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:173)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:226)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:205)
	at org.sonar.scanner.bootstrap.SpringScannerContainer.doAfterStart(SpringScannerContainer.java:350)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:226)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:205)
	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:142)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:226)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:205)
	at org.sonar.scanner.bootstrap.ScannerMain.runScannerEngine(ScannerMain.java:151)
	at org.sonar.scanner.bootstrap.ScannerMain.run(ScannerMain.java:66)
	at org.sonar.scanner.bootstrap.ScannerMain.main(ScannerMain.java:52)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(Unknown Source)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.lambda$executeTasks$3(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.executeTasks(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.doHandshake(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at java.base/sun.security.validator.Validator.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 22 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
	... 27 common frames omitted
```

**Desktop (please complete the following information):**
- OS: Linux (within the custom Docker image used by GitLab CI)
- SonarQube version: 2025.1.1
- cxx plugin version: 2.2.1.1225
- sonar-scanner version: (Please specify the exact version used in your Docker image)

**Additional context**
Our SonarQube instance is deployed within a Kubernetes environment. The sonar-scanner is executed from a GitLab job using a custom Docker image. We have attempted to resolve this by following the instructions in the SonarQube documentation regarding TLS certificate management (https://docs.sonarsource.com/sonarqube-server/10.8/analyzing-source-code/scanners/scanner-environment/manage-tls-certificates/), but the issue remains. This problem arose immediately after the upgrade to SonarQube 2025.1.1 from 8.0.1+546 and was not present with the older version and the same sonar-cxx plugin. This suggests a potential incompatibility or a change in SSL/TLS handling in the newer SonarQube version that is affecting the sonar-cxx plugin.

### PR DESCRIPTION
**Pull request by jenspopp**
Hi,

this is a first working version with ssl context. I configured it similar to sonar and it works on my test system. Tried to do as little code change as possible. 

close #2916

Please review and give feedback ;-)

- - -
This change is [Reviewable](https://reviewable.io/reviews/SonarOpenCommunity/sonar-cxx/3033)

### CODE REVIEW

File: cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/SonarServerWebApi.java [hunk 1]
```diff
@@ -115,8 +119,9 @@ private static String createUrl(String sonarUrl, String api, String language, St
    *
    * @throws IOException if an I/O error occurs when sending or receiving
    */
-  public static String get(String uri, String authorization) throws IOException {
-    HttpClient client = HttpClient.newHttpClient();
+  public String get(String uri, String authorization) throws IOException {
+//    if (uri==null || uri.isBlank()) return "";
```
Comment (guwirth) [inline cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/SonarServerWebApi.java]: commented out code

File: cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/SSLContextBuilder.java [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+import org.sonar.api.config.Configuration;
+
+import nl.altindag.ssl.SSLFactory;
+import nl.altindag.ssl.exception.GenericKeyStoreException;
+
+public class SSLContextBuilder {
+
+    private static final Logger LOG = LoggerFactory.getLogger(SSLContextBuilder.class);
+
+    public static final String SKIP_SYSTEM_TRUST_MATERIAL = "sonar.scanner.skipSystemTruststore";
```
Comment (guwirth) [inline cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/SSLContextBuilder.java]: Ok, seems to be according to SQ documentation

File: cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/SSLContextBuilder.java [hunk 3]
```diff
@@ -0,0 +1,109 @@
...
+
+    /**
+     * This is adapted from Sonar source...
+     * 
+     * @TODO: check if this can be grabbed from sonar
+     * @return
+     */
+    protected static SSLContext createSSLContext(Configuration config) {
+	var sslFactoryBuilder = SSLFactory.builder().withDefaultTrustMaterial();
+	var skipSystemTrustMaterial = config.getBoolean(SKIP_SYSTEM_TRUST_MATERIAL).orElse(false);
```
[the remark this answers is not in the document]
Comment (jenspopp) [reply cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/SSLContextBuilder.java]: Was default on SONAR, but set it to true. We assume that the truststore is set from sonar and is correct.

File: cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/SonarServerWebApi.java (hunk 1 above)
Comment (jenspopp) [reply cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/SonarServerWebApi.java]: Fixed, forgot to delete after fixing the tests

File: cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/CxxIssuesReportSensor.java [hunk 4]
```diff
@@ -80,26 +81,21 @@ public CxxIssuesReportSensor setWebApi(SonarServerWebApi webApi) {
...
     for (var report : reports) {
       executeReport(report);
     }
   }
 
-  private void downloadRulesFromServer(String url, String authenticationToken) {
+  private void downloadRulesFromServer(Configuration configuration) {
     try {
-      LOG.info("Downloading rules for '{}' from server '{}'", getRuleRepositoryKey(), url);
+        String url = configuration.get("sonar.host.url").orElse("http://localhost:9000");
```
[the remark this answers is not in the document]
Comment (jenspopp) [reply cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/CxxIssuesReportSensor.java]: Moved logging to SonarServerWebApi

File: cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/SSLContextBuilder.java [hunk 5]
```diff
@@ -0,0 +1,126 @@
...
+ * This program is distributed in the hope that it will be useful,
+ * but WITHOUT ANY WARRANTY; without even the implied warranty of
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+ * Lesser General Public License for more details.
+ *
+ * You should have received a copy of the GNU Lesser General Public License
+ * along with this program; if not, write to the Free Software Foundation,
+ * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+ */
+
```
Comment (guwirth) [inline cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/SSLContextBuilder.java]: Add link/text like here https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/RulesDefinitionXmlLoader.java

Comment (jenspopp) [reply cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/SSLContextBuilder.java]: Done
