### PR TITLE
Analysis does not continue after error (sonar.cxx.errorRecoveryEnabled=true)

### LINKED ISSUE #1386: Analysis does not continue after error (sonar.cxx.errorRecoveryEnabled=true)
Analysis does not continue after error (sonar.cxx.errorRecoveryEnabled=true)
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties#sonarcxxerrorrecoveryenabled

```
ERROR: Error during SonarQube Scanner execution
org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: xxx.h
	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:131)
	at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:164)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        ...
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        ...
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.IllegalArgumentException: Line 41 is out of range for file xxx.h. File has 40 lines.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at org.sonar.scanner.DefaultFileLinesContext.checkLineRange(DefaultFileLinesContext.java:70)
	at org.sonar.scanner.DefaultFileLinesContext.setIntValue(DefaultFileLinesContext.java:63)
	at org.sonar.cxx.sensors.visitors.CxxFileLinesVisitor.lambda$leaveFile$0(CxxFileLinesVisitor.java:185)
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at org.sonar.cxx.sensors.visitors.CxxFileLinesVisitor.leaveFile(CxxFileLinesVisitor.java:185)
	at com.sonar.sslr.impl.ast.AstWalker.walkAndVisit(AstWalker.java:71)
	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:110)
	... 33 more
```

### PR DESCRIPTION
**Pull request by guwirth**
- continue in case there is an error in CxxFileLinesVisitor (sonar.cxx.errorRecoveryEnabled=true)
- close #1386

---
This change is [Reviewable](https://reviewable.io/reviews/sonaropencommunity/sonar-cxx/1387)

### CODE REVIEW

File: cxx-sensors/src/main/java/org/sonar/cxx/sensors/visitors/CxxFileLinesVisitor.java [hunk 1]
```diff
@@ -74,8 +78,9 @@
    * @param fileLinesContextFactory container for linesOfCode, linesOfComments, executableLines
    * @param allLinesOfCode set of lines for a source file
    */
-  public CxxFileLinesVisitor(FileLinesContextFactory fileLinesContextFactory, SensorContext context,
+  public CxxFileLinesVisitor(CxxLanguage language, FileLinesContextFactory fileLinesContextFactory, SensorContext context,
```
Comment (Bertk) [inline cxx-sensors/src/main/java/org/sonar/cxx/sensors/visitors/CxxFileLinesVisitor.java]: I do not think that the CxxLanguage (C++, C) is helpful to fix this issue.

File: cxx-sensors/src/main/java/org/sonar/cxx/sensors/visitors/CxxFileLinesVisitor.java [hunk 2]
```diff
@@ -182,11 +187,30 @@ public void leaveFile(AstNode astNode) {
     }
     FileLinesContext fileLinesContext = fileLinesContextFactory.createFor(inputFile);
 
-    linesOfCode.stream().forEach(line -> fileLinesContext.setIntValue(CoreMetrics.NCLOC_DATA_KEY, line, 1));
-    linesOfComments.stream().forEach(line -> fileLinesContext.setIntValue(CoreMetrics.COMMENT_LINES_DATA_KEY, line, 1));
-    executableLines.stream().forEach(line -> fileLinesContext.setIntValue(CoreMetrics.EXECUTABLE_LINES_DATA_KEY,
-      line, 1));
-
+    try {
```
Comment (Bertk) [inline cxx-sensors/src/main/java/org/sonar/cxx/sensors/visitors/CxxFileLinesVisitor.java]: a single try/catch statement for the 3 metric updates would be sufficient.

File: cxx-sensors/src/main/java/org/sonar/cxx/sensors/visitors/CxxFileLinesVisitor.java (hunk 1 above)
Comment (guwirth) [reply cxx-sensors/src/main/java/org/sonar/cxx/sensors/visitors/CxxFileLinesVisitor.java]: Helper CxxUtils.validateRecovery(e, language); needs it.
