### PR TITLE
Fix #766: Handle relative report paths with backticks outside basedir.

### LINKED ISSUE #766: NullPointerException looking for CppCheck report
I'm getting a NPE when I attempt to run analysis on my project, with sonar-cxx 0.9.3.

```
INFO: Sensor CxxCoverageSensor (done) | time=1526ms
INFO: Sensor CxxCppCheckSensor
DEBUG: Using pattern 'null' to find reports
INFO: Analysis report generated in /home/gitlab-runner/builds/580bbdff/0/hidden/path/src/.sonar/batch-report
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 15.928s
INFO: Final Memory: 41M/110M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
org.sonar.api.utils.SonarException: Cannot feed the data into sonar, details: 'java.lang.NullPointerException'
        at org.sonar.plugins.cxx.utils.CxxReportSensor.analyse(CxxReportSensor.java:134)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)

.... snip ....

Caused by: java.lang.NullPointerException
        at org.apache.tools.ant.DirectoryScanner.setIncludes(DirectoryScanner.java:569)
        at org.sonar.plugins.cxx.utils.CxxReportSensor.getReports(CxxReportSensor.java:166)
        at org.sonar.plugins.cxx.utils.CxxReportSensor.analyse(CxxReportSensor.java:104)
        ... 31 more
```
I _am_ setting the report path in my properties file:
```
sonar.cxx.cppcheck.reportPath=../out/doc/cppcheck/*.xml
```

It looks like there's been a lot of refactoring going on in your repository here so the code that caused this may no longer exist, but maybe this problem is still there. In the code that went into 0.9.3, I'm not sure what would cause reportPath to be null, because (1) I'm setting it in my config, and (2) it's getting set to the default if it is null.

### PR DESCRIPTION
**Pull request by mjdetullio**
It was possible to have an NPE when normalizing backticks on relative
paths if the backticks moved the directory too far back.  This change
will handle invalid normalization of relative paths.

Normalization is reattempted against the absolute path, and if it is
still invalid then it is not given to the directory scanner, which does
not accept null elements.

### CODE REVIEW

File: sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/utils/CxxReportSensor.java [hunk 1]
```diff
@@ -152,24 +149,30 @@ protected String getStringProperty(String name, String def) {
...
-          return FilenameUtils.normalize(moduleBaseDir.getAbsolutePath() + File.separator + path);
+    List<String> reportPaths = Arrays.asList(settings.getStringArray(reportPathPropertyKey));
+    if (!reportPaths.isEmpty()) {
+      List<String> includes = new ArrayList<>();
+      for (String reportPath : reportPaths) {
+        // Normalization can return null if path is null, is invalid, or is a path with back-ticks outside known directory structure
+        String normalizedPath = FilenameUtils.normalize(reportPath);
+        if (normalizedPath != null && new File(normalizedPath).isAbsolute()) {
+          includes.add(normalizedPath);
+          continue;
```
Comment (guwirth) [inline sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/utils/CxxReportSensor.java]: @mjdetullio I'm not a fan of continue in loops. Think if / else if / else would be the same ....

**Comment by guwirth** [comment]
fix #766 together with #775
