### PR TITLE
workaround for 'forceZeroCoverage'

### LINKED ISSUE #909: figure out what to do with forceZeroCoverage feature that does not work anymore in batch side
- drop?
- or move to server side.

### LINKED ISSUE #999: coverage issues with SQ6.2
Integration tests measuring coverage are no more running with SQ6.2 (see log files of IT tests).

### PR DESCRIPTION
**Pull request by guwirth**
* add a FileLinesVisitor
* add 'sonar.cxx.coverage.forceZeroCoverage' again with PropertyDefinition
* close #999
* close #909

### CODE REVIEW

**Comment by guwirth** [comment]
@all ready to review. Brings back the `sonar.cxx.coverage.forceZeroCoverage` feature.

File: sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/metrics/FileLinesVisitor.java [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+import org.sonar.api.measures.FileLinesContext;
+import org.sonar.api.measures.FileLinesContextFactory;
+import org.sonar.cxx.api.CxxMetric;
+import org.sonar.squidbridge.SquidAstVisitor;
+
+/**
+ * Visitor that computes {@link CoreMetrics#NCLOC_DATA_KEY} and
+ * {@link CoreMetrics#COMMENT_LINES_DATA_KEY} metrics used by the DevCockpit.
+ */
+public class FileLinesVisitor extends SquidAstVisitor<Grammar> implements AstAndTokenVisitor {
```
Comment (jmecosta) [inline sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/metrics/FileLinesVisitor.java]: Should this be called filesexecutedlinesvisitor?

**Comment by guwirth** [comment]
I did a test with our projects: works fine for us.
