### PR TITLE
CxxIssuesReportSensor: use realPath as part of path normalization

### LINKED ISSUE #1651: WARN: Cannot find the file '...' in module '...' base dir '...', skipping violations.
### Description

If the source code is in subdirectories, the comparison of the paths is case-sensitive. (Also on Windows)

The output of MSBuild contains all paths in lowercase (see buildlog.log in log section). However, the project contains a subdirectory "Sources" in which all source files are located. This means that the files cannot be found.

### Steps to reproduce the problem

```PowerShell
PS > git clone https://github.com/rudolfgrauberger/sonar-cxx-examples.git
PS > cd sonar-cxx-examples/FolderStructureCpp
PS > MSBuild.exe .\FolderStructureCpp.vcxproj /t:rebuild /p:Configuration=Release /fileLogger "/fileLoggerParameters:LogFile=buildlog.log;Verbosity=normal;Encoding=UTF-8"
PS > sonar-scanner
```

### Expected behavior

That the compiler sensor finds the file and analyzes it. Under Windows the upper and lower case "actually" doesn't matter. 

If I have seen this correctly here (#155), then it was already a topic once.  Could it be that it was lost during the last refactoring (#1180)?

### Actual behavior

Because the file is not found, it is not analyzed.

### Known workarounds

Not good, but works...

#### Rename folder to lower case
```PowerShell
PS > mv Sources sources_temp
PS > mv sources_temp sources
```
### LOG file

**stdout**
```
...
INFO: Searching reports by relative path with basedir 'E:\Dev\Source\Repos\sonar-cxx-samples\FolderStructureCpp' and search prop 'sonar.cxx.vc.reportPath'
INFO: Parser will parse '1' report file(s)
INFO: Processing report 'E:\Dev\Source\Repos\sonar-cxx-samples\FolderStructureCpp\buildlog.log'
INFO: Parsing 'Visual C++' initialized with report 'E:\Dev\Source\Repos\sonar-cxx-samples\FolderStructureCpp\buildlog.log', Charset= 'UTF-8'
INFO: Using pattern : '(.*>)?\x20*(?<file>.*)\((?<line>\d+)\):\x20warning\x20(?<id>C\d+):(?<message>.*)'
WARN: Cannot find the file 'e:\dev\source\repos\sonar-cxx-samples\folderstructurecpp\sources\main.cpp' in module 'FolderStructureCpp' base dir 'E:\Dev\Source\Repos\sonar-cxx-samples\FolderStructureCpp', skipping violations.
INFO: CXX-COMPILER-VC processed = 0
...
```

**buildlog.log**
```
Der Buildvorgang wurde am 03.01.2019 01:47:41 gestartet.
Projekt "E:\Dev\Source\Repos\sonar-cxx-samples\FolderStructureCpp\FolderStructureCpp.vcxproj" auf Knoten "1", rebuild Ziel(e).
_PrepareForClean:
  Die Datei "Release\FolderSt.67F13409.tlog\FolderStructureCpp.lastbuildstate" wird gelöscht.
InitializeBuildStatus:
  "Release\FolderSt.67F13409.tlog\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\CL.exe /c /IIncludes /Zi /nologo /W4 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D CODE_ANALYSIS /D _MBCS /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Release\\" /Fd"Release\vc141.pdb" /Gd /TP /analyze /analyze:quiet /analyze:plugin"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\EspXEngine.dll" /analyze:plugin"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\localespc.dll" /FC /errorReport:queue  /analyze:ruleset"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Static Analysis Tools\Rule Sets\NativeRecommendedRules.ruleset" Sources/main.cpp Sources/TestClass.cpp
  main.cpp
e:\dev\source\repos\sonar-cxx-samples\folderstructurecpp\sources\main.cpp(3): warning C4100: "argv": Unreferenzierter formaler Parameter [E:\Dev\Source\Repos\sonar-cxx-samples\FolderStructureCpp\FolderStructureCpp.vcxproj]
e:\dev\source\repos\sonar-cxx-samples\folderstructurecpp\sources\main.cpp(3): warning C4100: "argc": Unreferenzierter formaler Parameter [E:\Dev\Source\Repos\sonar-cxx-samples\FolderStructureCpp\FolderStructureCpp.vcxproj]
  TestClass.cpp
  Kompilieren...
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\link.exe /ERRORREPORT:QUEUE /OUT:"E:\Dev\Source\Repos\sonar-cxx-samples\FolderStructureCpp\Release\FolderStructureCpp.exe" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FULL /PDB:"E:\Dev\Source\Repos\sonar-cxx-samples\FolderStructureCpp\Release\FolderStructureCpp.pdb" /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:\Dev\Source\Repos\sonar-cxx-samples\FolderStructureCpp\Release\FolderStructureCpp.lib" /MACHINE:X86 /SAFESEH Release\main.obj
  Release\TestClass.obj
  Code wird generiert.
  All 2 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Codegenerierung ist abgeschlossen.
  FolderStructureCpp.vcxproj -> E:\Dev\Source\Repos\sonar-cxx-samples\FolderStructureCpp\Release\FolderStructureCpp.exe
FinalizeBuildStatus:
  Die Datei "Release\FolderSt.67F13409.tlog\unsuccessfulbuild" wird gelöscht.
  Aktualisieren des Timestamps von "Release\FolderSt.67F13409.tlog\FolderStructureCpp.lastbuildstate".
Die Erstellung von Projekt "E:\Dev\Source\Repos\sonar-cxx-samples\FolderStructureCpp\FolderStructureCpp.vcxproj" ist abgeschlossen (rebuild Ziel(e)).


Der Buildvorgang wurde erfolgreich ausgeführt.

"E:\Dev\Source\Repos\sonar-cxx-samples\FolderStructureCpp\FolderStructureCpp.vcxproj" (rebuild Ziel) (1) ->
(ClCompile Ziel) -> 
  e:\dev\source\repos\sonar-cxx-samples\folderstructurecpp\sources\main.cpp(3): warning C4100: "argv": Unreferenzierter formaler Parameter [E:\Dev\Source\Repos\sonar-cxx-samples\FolderStructureCpp\FolderStructureCpp.vcxproj]
  e:\dev\source\repos\sonar-cxx-samples\folderstructurecpp\sources\main.cpp(3): warning C4100: "argc": Unreferenzierter formaler Parameter [E:\Dev\Source\Repos\sonar-cxx-samples\FolderStructureCpp\FolderStructureCpp.vcxproj]

    2 Warnung(en)
    0 Fehler

Verstrichene Zeit 00:00:03.43
```

### Related information
* Windows version: 10 x64 (1809)
* cxx plugin version: V1.2.1
* SonarQube (in Docker) version:  7.4.0.18908
* Visual Studio version: 2017 Enterprise

### PR DESCRIPTION
**Pull request by ivangalkin**
* introduce the fallback for the lookup of `InputFile`s: if generic lookup was not successful, try it with the `Path::realPath()`

resolves #1651 

@rudolfgrauberger could you please test the snapshot on your local setup?
@guwirth how do we suppose to test things like that?

---
This change is [Reviewable](https://reviewable.io/reviews/sonaropencommunity/sonar-cxx/1653)

### CODE REVIEW

**Comment by rudolfgrauberger** [comment]
I have tested your changes to some projects and it works perfektly. Works no matter how I write the folder name now e.g. "Sources", "sources" or "SouRcEs". As I expect it under Windows. 

Thank you very much!

**Comment by guwirth** [comment]
@ivangalkin I like the solution. Question is if there is a big performance impact? Think not all users needs it?

> how do we suppose to test things like that?

Think we have two CI systems with Travis and AppVeyor on Linux and Windows. We can test it by adding an integration test.

**Comment by ivangalkin** [comment]
@guwirth I came to the conclusion, that using the real path (`Path::toRealPath()`) is as error-prone as using canonical path ( #1574/ #1575 ). So I believe it's better not to rely on the real path completely, but rather to use it as a "second try". In that case there is no performance impact for the existing paths. But yes, the query of non-existing path requires more overhead now.

I like the idea to use it in `CxxIssuesReportSensor::getInputFileIfInProject()`, since the normalization might be useful for more than one sensor. If it's not true, we can tweak VC-related sensor only.

**Comment by guwirth** [comment]
@ivangalkin yes makes sense. Do you like to write a test or should I merge it as it is?

File: cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/CxxIssuesReportSensor.java [hunk 1]
```diff
@@ -145,8 +145,8 @@ private InputFile getInputFileTryRealPath(SensorContext sensorContext, String pa
       realPath = absolutePath.toRealPath(LinkOption.NOFOLLOW_LINKS);
     } catch (IOException e) {
       if (LOG.isDebugEnabled()) {
-        LOG.debug("Unable to get the real path: module {}, baseDir {}, path {}", sensorContext.module().key(),
-            sensorContext.fileSystem().baseDir(), path);
+        LOG.debug("Unable to get the real path: module '{}', baseDir '{}', path '{}', excepiton '{}'",
```
Comment (rudolfgrauberger) [inline cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/CxxIssuesReportSensor.java]: Here is an spelling error in 'excepiton'
