### PR TITLE
replacing text macros (C++11 syntax)

### LINKED ISSUE #951: C++11 preprocessor syntax not supported
See _Replacing text macros_ [syntax 4](http://en.cppreference.com/w/cpp/preprocessor/replace)

> #define identifier( ... ) replacement-list

CXX Plug-in fails with syntax 4 – sample code:
```
#define showlist(...) puts(#__VA_ARGS__)
showlist(1, "x", int); // expands to puts("1, \"x\", int")
showlist("x");         // expands to puts("\"x\"")
showlist();            // expands to puts("")

```
SSLR toolkit output:
```
com.sonar.sslr.api.RecognitionException: Parse error at line 4 column 10:

    2: puts ( "1,\"x\",int" );
    3: puts ( "\"x\"" );
  -->  puts (    ;
    5: 
    6: EOF

	at org.sonar.sslr.internal.vm.Machine.parse(Machine.java:74)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:87)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:81)
	at org.sonar.sslr.internal.toolkit.SourceCodeModel.setSourceCode(SourceCodeModel.java:62)
	at org.sonar.sslr.internal.toolkit.ToolkitPresenter.onSourceCodeParseButtonClick(ToolkitPresenter.java:124)
	at org.sonar.sslr.internal.toolkit.ToolkitViewImpl$5.actionPerformed(ToolkitViewImpl.java:203)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by Bertk**
close #951

### CODE REVIEW

File: cxx-squid/src/main/java/org/sonar/cxx/preprocessor/CxxPreprocessor.java [hunk 1]
```diff
@@ -908,6 +909,22 @@ private int matchArguments(List<Token> tokens, List<Token> arguments) {
       }
     }
 
+    // replace # with "" if sequence HASH BR occurs for body HASH __VA_ARGS__    
+    if (newTokens.size() > 3 && newTokens.get(newTokens.size() - 1).getType() == BR_RIGHT && newTokens.get(newTokens.size() - 2).getType() == HASH) {
```
Comment (guwirth) [inline cxx-squid/src/main/java/org/sonar/cxx/preprocessor/CxxPreprocessor.java]: @Bertk don't know if there is really a performance difference? Would check first for # and then for comma. Think a hit for # is less likely.

**Comment by guwirth** [comment]
@Bertk looks good, see my review hint.

File: cxx-squid/src/main/java/org/sonar/cxx/preprocessor/CxxPreprocessor.java (hunk 1 above)
Comment (jmecosta) [inline cxx-squid/src/main/java/org/sonar/cxx/preprocessor/CxxPreprocessor.java]: at least move the newTokens.size() to temporary variable so that we dont count the tokes for each condition?

Comment (Bertk) [inline cxx-squid/src/main/java/org/sonar/cxx/preprocessor/CxxPreprocessor.java]: @jmecosta 
I agree. The methode replaceParams needs some refactoring but I think this effort should be postponed until we know how we continue with the preprocessor design.
